### ISSUE TITLE
Fail to run `clang-format`

### ISSUE THREAD

**Issue by otavio** [katyo/zephyr-rtos.nix#2]
The location of `ld-linux-x86-64.so.2` set as `/lib64/ld-linux-x86-64.so.2` causes `clang-format` to fail.
 
```
% clang-format
Traceback (most recent call last):
  File ".../.venv/bin/clang-format", line 8, in <module>
    sys.exit(clang_format())
  File ".../.venv/lib/python3.10/site-packages/clang_format/__init__.py", line 21, in clang_format
    raise SystemExit(_run("clang-format"))
  File ".../.venv/lib/python3.10/site-packages/clang_format/__init__.py", line 11, in _run
    return subprocess.call([executable] + sys.argv[1:])
  File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '.../.venv/lib/python3.10/site-packages/clang_format/data/bin/clang-format'
```

**Comment by otavio** [comment]
One possible solution would be use `buildFHSUserEnv` so `nix-ld` workaround it. How does it sounds?

**Comment by katyo** [comment]
I would like to avoid FHS env. May be more proper solution is using patchelf to fix executables.

**Comment by katyo** [comment]
I am also considering the possibility to provide zephyr sources and python dependencies via nix.

**Comment by katyo** [comment]
@otavio I added a quick fix for that. Before try it you need remove `.venv` directory.

**Comment by otavio** [comment]
The fix was successful. It would be better to provide Zephyr sources and Python dependencies via Nix, indeed.
